In [37]:
import os
import langchain
from langchain.text_splitter import TokenTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings

embeddings = HuggingFaceEmbeddings()
text_splitter = TokenTextSplitter(chunk_size=110, chunk_overlap=20)

def encode_text(text):
    op_texts = text_splitter.split_text(text)
    # if len(op_texts) >1:
    #     print(len(op_texts))
    embeds = embeddings.embed_query(text)
    return embeds

In [41]:
import pandas as pd
df = pd.read_csv('../data/IMDB-Movie-Data.csv')
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [39]:
type(df['Description'][0])

str

In [46]:
df['Combined'] = "Title: "+df["Title"] + "\nGenre: " + df["Genre"]+ "\nDescription: " + df["Description"]+ "\nYear: " + str(df["Year"])+ "\nActors: " + df["Actors"]+ "\nDirector: " + df["Director"]

In [47]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Combined
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,"Title: Guardians of the Galaxy\nGenre: Action,..."
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,"Title: Prometheus\nGenre: Adventure,Mystery,Sc..."
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,"Title: Split\nGenre: Horror,Thriller\nDescript..."
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,"Title: Sing\nGenre: Animation,Comedy,Family\nD..."
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,"Title: Suicide Squad\nGenre: Action,Adventure,..."

In [48]:
df['desc_embedding'] = df['Combined'].apply(encode_text)

In [49]:
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore,Combined,desc_embedding
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0,"Title: Guardians of the Galaxy\nGenre: Action,...","[0.03254978358745575, 0.04438316449522972, 0.0..."
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0,"Title: Prometheus\nGenre: Adventure,Mystery,Sc...","[0.03714342042803764, 0.02058291807770729, 0.0..."
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0,"Title: Split\nGenre: Horror,Thriller\nDescript...","[0.036155033856630325, 0.018174979835748672, -..."
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0,"Title: Sing\nGenre: Animation,Comedy,Family\nD...","[0.026934001594781876, 0.06733153760433197, 0...."
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0,"Title: Suicide Squad\nGenre: Action,Adventure,...","[0.01157628558576107, 0.0347396619617939, 0.00..."

In [50]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore', 'Combined', 'desc_embedding'],
      dtype='object')

In [51]:
df = df.drop(['Rank', 'Genre', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore','Combined'], axis=1)

In [52]:
df.head()

,Title,Description,desc_embedding
0,Guardians of the Galaxy,A group of intergalactic criminals are forced ...,"[0.03254978358745575, 0.04438316449522972, 0.0..."
1,Prometheus,"Following clues to the origin of mankind, a te...","[0.03714342042803764, 0.02058291807770729, 0.0..."
2,Split,Three girls are kidnapped by a man with a diag...,"[0.036155033856630325, 0.018174979835748672, -..."
3,Sing,"In a city of humanoid animals, a hustling thea...","[0.026934001594781876, 0.06733153760433197, 0...."
4,Suicide Squad,A secret government agency recruits some of th...,"[0.01157628558576107, 0.0347396619617939, 0.00..."

In [53]:
file_path = 'movies_vec.json'
df.to_json(file_path, orient='records', lines=True)